services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/bidding
    depends_on:
      - db

    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bidding
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql

volumes:
  db-data:
